/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectakhir;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.DefaultButtonModel;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class cekout extends javax.swing.JFrame {
Connection con;
Statement stm;
ResultSet rs;
String sql;
 int jumlahPembelian;
 int totalHarga;
 String idhpp=null;
  int update;
private static String namahp;
private static int hargahp;
public static int stok;
public static String logiinAs;
private JSpinner spinner;
private SpinnerNumberModel spinnerModel;

    public cekout(String namahp,int hargahp,int stok,String logiinAs) {
        this.namahp=namahp;
        this.hargahp=hargahp;
        this.stok=stok;
        this.logiinAs=logiinAs;
        initComponents();
        koneksi DB= new koneksi();
        DB.config();
       con=DB.con;
        stm=DB.stm;
       txtmerek.setText(namahp);
       login.setText(logiinAs);
       jumlah();
       keterangan();
       // loadtable();
        pro();
       
    }

    

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnohp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txalamat = new javax.swing.JTextArea();
        btnhome = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtmerek = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtalamat = new javax.swing.JScrollPane();
        txtket = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        spin1 = new javax.swing.JSpinner();
        idpembeli = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        idhp = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        datapembeli = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnsimpan1 = new javax.swing.JButton();
        btnsimpan2 = new javax.swing.JButton();
        cetak = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tanggal = new javax.swing.JTextField();
        napem = new javax.swing.JTextField();
        nohp = new javax.swing.JTextField();
        namahpfiks = new javax.swing.JTextField();
        jumlahhp = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        totalbayar = new javax.swing.JTextField();
        kembali = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        kasir = new javax.swing.JTextField();
        no = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        login = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        kembalian = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        bayar = new javax.swing.JTextField();
        tgl_chos = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("DATA PELANGGAN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, -1, -1));
        jPanel1.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 54, 193, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Alamat :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 154, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("No hp :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 116, -1, -1));
        jPanel1.add(txtnohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 116, 193, -1));

        txalamat.setColumns(20);
        txalamat.setRows(5);
        jScrollPane1.setViewportView(txalamat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 154, 241, -1));

        btnhome.setBackground(new java.awt.Color(0, 204, 204));
        btnhome.setText("Home");
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 255));
        jLabel11.setText("Jumlah Pembelian :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 486, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 255, 255));
        jLabel12.setText("Merek HP/id :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 333, -1, -1));

        txtmerek.setEditable(false);
        jPanel1.add(txtmerek, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 333, 126, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 255, 255));
        jLabel13.setText("Sfesifikasi");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 371, -1, -1));

        txtket.setEditable(false);
        txtket.setBackground(new java.awt.Color(51, 204, 255));
        txtket.setColumns(20);
        txtket.setRows(5);
        txtalamat.setViewportView(txtket);

        jPanel1.add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 371, 233, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 255, 255));
        jLabel14.setText("Total :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 519, -1, -1));

        txttotal.setEditable(false);
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });
        jPanel1.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, 202, -1));
        jPanel1.add(spin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 486, -1, -1));

        idpembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpembeliActionPerformed(evt);
            }
        });
        jPanel1.add(idpembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 85, 193, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 255, 255));
        jLabel16.setText("ID pembeli :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 85, -1, -1));

        idhp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idhpActionPerformed(evt);
            }
        });
        jPanel1.add(idhp, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 333, 50, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(datapembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(datapembeli, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 54, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("Nama pembeli :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 54, -1, -1));

        btnsimpan1.setBackground(new java.awt.Color(0, 204, 204));
        btnsimpan1.setText("submit");
        btnsimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpan1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnsimpan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 73, -1));

        btnsimpan2.setBackground(new java.awt.Color(0, 204, 204));
        btnsimpan2.setText("hitung");
        btnsimpan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpan2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnsimpan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 610, 73, -1));

        cetak.setBackground(new java.awt.Color(204, 204, 204));
        cetak.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("--------------------------------------------------------------------------------------------");
        cetak.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 95, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText(" NO : ");
        cetak.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("No hp                     :");
        cetak.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 146, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Nama Pembeli         :");
        cetak.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 123, 122, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setText("Nama HP                :");
        cetak.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 169, 122, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setText("Jumlah Barang         :");
        cetak.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 192, -1, -1));

        jLabel19.setText("--------------------------------------------------------------------------------------------");
        cetak.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 227, -1, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setText("Total Pembelian       :");
        cetak.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 247, -1, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel21.setText("Total Bayar             :");
        cetak.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 275, 121, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel22.setText("Kembali                  :");
        cetak.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 303, 121, -1));

        jLabel23.setText("--------------------------------------------------------------------------------------------");
        cetak.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 347, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel24.setText("TOKO HP AMAN ");
        cetak.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 10, -1, -1));

        jLabel25.setText("\"Anda Puas Kami Senang\"");
        cetak.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 130, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel26.setText("Terimakasih sudah Berbelanja");
        cetak.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 372, -1, -1));

        tanggal.setEditable(false);
        tanggal.setBackground(new java.awt.Color(204, 204, 204));
        tanggal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalActionPerformed(evt);
            }
        });
        cetak.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 207, -1));

        napem.setEditable(false);
        napem.setBackground(new java.awt.Color(204, 204, 204));
        napem.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        napem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                napemActionPerformed(evt);
            }
        });
        cetak.add(napem, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 123, 211, -1));

        nohp.setEditable(false);
        nohp.setBackground(new java.awt.Color(204, 204, 204));
        nohp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        nohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nohpActionPerformed(evt);
            }
        });
        cetak.add(nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 146, 211, -1));

        namahpfiks.setEditable(false);
        namahpfiks.setBackground(new java.awt.Color(204, 204, 204));
        namahpfiks.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        namahpfiks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namahpfiksActionPerformed(evt);
            }
        });
        cetak.add(namahpfiks, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 169, 211, -1));

        jumlahhp.setEditable(false);
        jumlahhp.setBackground(new java.awt.Color(204, 204, 204));
        jumlahhp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jumlahhp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahhpActionPerformed(evt);
            }
        });
        cetak.add(jumlahhp, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 192, 211, -1));

        total.setEditable(false);
        total.setBackground(new java.awt.Color(204, 204, 204));
        total.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        cetak.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 247, 207, -1));

        totalbayar.setEditable(false);
        totalbayar.setBackground(new java.awt.Color(204, 204, 204));
        totalbayar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        totalbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalbayarActionPerformed(evt);
            }
        });
        cetak.add(totalbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 275, 208, -1));

        kembali.setEditable(false);
        kembali.setBackground(new java.awt.Color(204, 204, 204));
        kembali.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        cetak.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 303, 208, -1));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel28.setText("Kasir                      :");
        cetak.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 324, 121, -1));

        kasir.setEditable(false);
        kasir.setBackground(new java.awt.Color(204, 204, 204));
        kasir.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        kasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kasirActionPerformed(evt);
            }
        });
        cetak.add(kasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 324, 202, -1));
        cetak.add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 80, 17));

        jPanel1.add(cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, 410));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("Tanggal");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 265, -1, -1));

        jButton3.setText("CETAK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, 101, 43));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setText("Nama Kasir :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 295, -1, -1));

        login.setEditable(false);
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 295, 193, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 255, 255));
        jLabel15.setText("Kembalian   :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 580, -1, -1));

        kembalian.setEditable(false);
        kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalianActionPerformed(evt);
            }
        });
        jPanel1.add(kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, 200, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 255, 255));
        jLabel29.setText("Total  bayar:");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 550, -1, -1));

        bayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bayarMouseClicked(evt);
            }
        });
        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });
        jPanel1.add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 550, 200, -1));
        jPanel1.add(tgl_chos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 902, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsimpan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpan2ActionPerformed
int bayar1=Integer.parseInt(bayar.getText());
        int kembalian1 =  bayar1-totalHarga;
        kembalian.setText(String.valueOf(kembalian1));       
        
    }//GEN-LAST:event_btnsimpan2ActionPerformed

    private void btnsimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpan1ActionPerformed
        insert();
         update();
    }//GEN-LAST:event_btnsimpan1ActionPerformed

    private void idhpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idhpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idhpActionPerformed

    private void idpembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idpembeliActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        menuutama1 mn=new menuutama1();
        mn.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnhomeActionPerformed

    private void tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalActionPerformed

    private void napemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_napemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_napemActionPerformed

    private void nohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nohpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nohpActionPerformed

    private void namahpfiksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namahpfiksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namahpfiksActionPerformed

    private void jumlahhpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahhpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahhpActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void totalbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalbayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalbayarActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembaliActionPerformed

    private void kasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kasirActionPerformed

    private void kembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembalianActionPerformed

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarActionPerformed

    private void bayarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bayarMouseClicked
        jumlahPembelian = (int) spin1.getValue();
        totalHarga = hargahp * jumlahPembelian;
        txttotal.setText(String.valueOf(totalHarga));
    }//GEN-LAST:event_bayarMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//        MessageFormat header=new MessageFormat("Table Laporan");
//        MessageFormat footer=new MessageFormat("nugas nugas ");
//        try{
//            PrintRequestAttributeSet set=new HashPrintRequestAttributeSet();
//            cetak.print(JPanel.PrintMode.FIT_WIDTH, header, footer,true, set,true);
//            JOptionPane.showMessageDialog(null, "print succes");
//        }catch(java.awt.print.PrinterException e){
//            JOptionPane.showMessageDialog(null, "print gagal");
//        }
printRecord(cetak);
    }//GEN-LAST:event_jButton3ActionPerformed
 public void loadtable(){
     
        DefaultTableModel model=new DefaultTableModel();
        
         model.addColumn("no");
          model.addColumn("No Faktur");
         model.addColumn("Nama Pembeli");
        model.addColumn("ID Pembeli");
          model.addColumn("No handphone");
          model.addColumn("Alamat");
        model.addColumn("Nama HP");
        model.addColumn("Harga");
        model.addColumn("Jumlah ");
        model.addColumn("Total Bayar");
        
        try{
            int no=1;
            sql="Select nofak,namapembeli,pembeli.idpembeli,nohp,pembeli.alamatpembeli,"
                    + "namhp,harga,jumlahbeli,total from penjualan inner join pembeli,"
                    + "datahp where penjualan.idpembeli=pembeli.idpembeli and penjualan.idhp=datahp.idhp";
            rs=stm.executeQuery(sql);
            while(rs.next()){
                model.addRow(new Object[]{no++, rs.getInt(1), rs.getString(2),rs.getInt(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getInt(7),rs.getInt(8),rs.getInt(9)});
          
            } 
       // tbpenjualan.setModel(model);
            }catch(Exception e){
    JOptionPane.showConfirmDialog(this,e.getMessage());
     }

        
    }
  public void pro(){
        ImageIcon img=new ImageIcon("C:\\Users\\HP\\Downloads\\datapembeli.png");
        Image icon=img.getImage();
      
       Image scale=icon.getScaledInstance( datapembeli.getWidth(),datapembeli.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon baru= new ImageIcon(scale);
      datapembeli.setIcon(baru);

   }  public void update1(){
   //Js Area=txtalamat.getViewport().getView();
      jumlahPembelian = (int) spin1.getValue();
  totalHarga = hargahp * jumlahPembelian;
txttotal.setText(String.valueOf(totalHarga));
        try{
         sql="UPDATE pembeli  SET namapembeli='"+txtnama.getText()
                 +"',alamatpembeli='"+txalamat.getText()
                 +"',nohp='"+txtnohp.getText()+"' WHERE idpembeli='"+idpembeli.getText()+"'";
       
            java.sql.PreparedStatement pst=con.prepareStatement(sql);
            pst.execute();
//            loadtable();
           JOptionPane.showConfirmDialog(null, "Data berhasil di update");
        }catch(Exception e){
            JOptionPane.showConfirmDialog(null, e.getMessage());
        }
        try{
            sql="UPDATE penjualan set jumlahbeli='"+jumlahPembelian+"',total='"+totalHarga+"'where idpembeli='"+idpembeli.getText()+"'";
            java.sql.PreparedStatement pst=con.prepareStatement(sql);
            pst.execute();
         //   loadtable();
          System.out.println(jumlahPembelian);
           //  JOptionPane.showConfirmDialog(null, "Data berhasil di update");
        }catch(Exception e){
            JOptionPane.showConfirmDialog(null, e.getMessage());
        }
  }
    public void keterangan(){
    String keterangan=null;
       try{
            sql="select keterangan from datahp where namhp='"+txtmerek.getText()+"'";
        
           rs=stm.executeQuery(sql);
           while(rs.next()){
               keterangan=rs.getString("keterangan");
               txtket.setText(keterangan);
               
           }
        }catch(Exception e){
            JOptionPane.showConfirmDialog(this, e.getMessage());
        } 
       try{
            sql="select idhp from datahp where namhp='"+txtmerek.getText()+"'";
        
           rs=stm.executeQuery(sql);
           while(rs.next()){
               idhpp=rs.getString("idhp");
               idhp.setText(idhpp);
           }
        }catch(Exception e){
            JOptionPane.showConfirmDialog(this, e.getMessage());
        }
    }
   
    public void jumlah(){
        int min=0;
        int max=stok;
        int langkah=1;
        
    spinnerModel=new SpinnerNumberModel(stok,min,max,langkah);
   spin1.setModel(spinnerModel);
    }
    public void insert(){
     if(stok==0){
   int i =JOptionPane.showConfirmDialog(this,"Stok Habis,kembali ke menu utama?" );
    if(i==JOptionPane.YES_OPTION){
         menuutama1 mn=new menuutama1();
        mn.setVisible(true);
        dispose();
    }else if(i==JOptionPane.NO_OPTION){
         txtnama.setText("");
         txtnohp.setText("");
         idpembeli.setText("");
         txalamat.setText("");
         tgl_chos.setDate(null);
         txttotal.setText("");
         bayar.setText("");
         kembalian.setText("");
     }else if(i==JOptionPane.CANCEL_OPTION){
         txtnama.setText("");
         txtnohp.setText("");
         idpembeli.setText("");
         txalamat.setText("");
         tgl_chos.setDate(null);
         txttotal.setText("");
         bayar.setText("");
         kembalian.setText("");
    }
    }else{
          tanggal.setText(tgl_chos.getDate().toString());
        napem.setText(txtnama.getText());
        nohp.setText(txtnohp.getText());
        namahpfiks.setText(txtmerek.getText());
        jumlahhp.setText(String.valueOf(jumlahPembelian));
        total.setText(String.valueOf(totalHarga));
        totalbayar.setText(bayar.getText());
        kembali.setText(kembalian.getText());
        kasir.setText(login.getText());
        int idd=Integer.parseInt(idpembeli.getText());
         try{
            sql="select nofak from penjualan where idpembeli='"+idd+"'";
        rs=stm.executeQuery(sql);
        int nofakk = 0;
           while(rs.next()){
               nofakk=rs.getInt("nofak");
              }no.setText(String.valueOf(nofakk));
        }catch(Exception e){
            JOptionPane.showConfirmDialog(this, e.getMessage());
        }
     try{
          sql="INSERT INTO pembeli values('"+idpembeli.getText()+"','"+txtnama.getText()+"',"
                  + "'"+txalamat.getText()+"','"+txtnohp.getText()+"')";
           java.sql.PreparedStatement pst=con.prepareStatement(sql);
           pst.execute();
         //loadtable();
           JOptionPane.showConfirmDialog(this, "Data berhasil disimpan");
       }catch(Exception e){
           JOptionPane.showConfirmDialog(this,e.getMessage());
       }
     try{
            sql="INSERT INTO penjualan(idpembeli,idhp,jumlahbeli,tanggal,total) VALUES ('"+idpembeli.getText()+"','"+idhp.getText()+"','"+jumlahPembelian+"','"+tgl_chos.getDate().toString()+"','"+totalHarga+"')";
            java.sql.PreparedStatement pst=con.prepareStatement(sql);
           pst.execute();
             // loadtable();
        }catch(Exception e){
             JOptionPane.showConfirmDialog(this,e.getMessage());
        }
    
    }
    
}
    public void update(){
        update=stok-jumlahPembelian; 
        
         try{
            sql="UPDATE datahp  SET stok='"+update+"' WHERE idhp='"+idhpp+"'";
            java.sql.PreparedStatement pst=con.prepareStatement(sql);
            pst.execute();
 }catch(Exception e){
            JOptionPane.showConfirmDialog(null, e.getMessage());
        }
    }
    
 public void inserCetak(){
     String no="";
 }
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cekout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cekout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cekout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cekout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cekout(namahp,hargahp,stok,logiinAs).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bayar;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnsimpan1;
    private javax.swing.JButton btnsimpan2;
    private javax.swing.JPanel cetak;
    private javax.swing.JLabel datapembeli;
    private javax.swing.JTextField idhp;
    private javax.swing.JTextField idpembeli;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlahhp;
    private javax.swing.JTextField kasir;
    private javax.swing.JTextField kembali;
    private javax.swing.JTextField kembalian;
    private javax.swing.JTextField login;
    private javax.swing.JTextField namahpfiks;
    private javax.swing.JTextField napem;
    private javax.swing.JLabel no;
    private javax.swing.JTextField nohp;
    private javax.swing.JSpinner spin1;
    private javax.swing.JTextField tanggal;
    private com.toedter.calendar.JDateChooser tgl_chos;
    private javax.swing.JTextField total;
    private javax.swing.JTextField totalbayar;
    private javax.swing.JTextArea txalamat;
    private javax.swing.JScrollPane txtalamat;
    private javax.swing.JTextArea txtket;
    private javax.swing.JTextField txtmerek;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnohp;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables

    private void printRecord(JPanel panel){
        PrinterJob printerJob=PrinterJob.getPrinterJob();
        printerJob.setJobName("Print Record");
        printerJob.setPrintable(new Printable() {
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                if(pageIndex >0){
                    return Printable.NO_SUCH_PAGE;
                }
                Graphics2D graphics2D =(Graphics2D)graphics;
                graphics2D.translate(pageFormat.getImageableX()*2,pageFormat.getImageableY()*2);
                graphics2D.scale(0.5, 0.5);
                
                panel.paint(graphics2D);
                return Printable.PAGE_EXISTS;
            }
        });
        boolean returningResult=printerJob.printDialog();
        
        if(returningResult){
            try{
                printerJob.print();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Gagal");
            }
        }
    } 
  
}
