/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectakhir;

import java.awt.Color;
import java.awt.Image;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;

/**
 *
 * @author HP
 */
public class login extends javax.swing.JFrame {
Connection con;
Statement stm;
ResultSet rs;

String sql;
    public login() {
        initComponents();
        setLocationRelativeTo(null);
        koneksi k =new koneksi();
        k.config();
       con=k.con;
    stm=k.stm;
//image();
//image2();
image3();
image6();

placeholder();

    }
    public void placeholder(){
   txtuser.setText("*Masukkan Username");
   txtuser.setCaretPosition(0);
txtpas.setEchoChar((char)0);
txtpas.setText("*Masukkan Password");

    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtbuat = new javax.swing.JTextField();
        txtuser = new javax.swing.JTextField();
        txtpas = new javax.swing.JPasswordField();
        btnlogin = new javax.swing.JToggleButton();
        aman1 = new javax.swing.JLabel();
        aman = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lihat = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        ntsee = new javax.swing.JLabel();
        lihatlah = new javax.swing.JPanel();
        see = new javax.swing.JLabel();
        loginas = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel4.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setLayout(null);

        txtbuat.setEditable(false);
        txtbuat.setBackground(new java.awt.Color(0, 204, 204));
        txtbuat.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtbuat.setForeground(new java.awt.Color(51, 51, 51));
        txtbuat.setText(" Buat akun");
        txtbuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtbuatMouseClicked(evt);
            }
        });
        txtbuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuatActionPerformed(evt);
            }
        });
        jPanel3.add(txtbuat);
        txtbuat.setBounds(49, 274, 74, 22);

        txtuser.setBackground(new java.awt.Color(0, 204, 204));
        txtuser.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        txtuser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtuser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtuserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtuserFocusLost(evt);
            }
        });
        txtuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtuserMouseClicked(evt);
            }
        });
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        jPanel3.add(txtuser);
        txtuser.setBounds(49, 99, 189, 36);

        txtpas.setBackground(new java.awt.Color(0, 204, 204));
        txtpas.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtpas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpasFocusLost(evt);
            }
        });
        txtpas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpasMouseClicked(evt);
            }
        });
        txtpas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasActionPerformed(evt);
            }
        });
        jPanel3.add(txtpas);
        txtpas.setBounds(49, 182, 189, 36);

        btnlogin.setBackground(new java.awt.Color(0, 204, 204));
        btnlogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnlogin.setText("login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel3.add(btnlogin);
        btnlogin.setBounds(73, 229, 156, 23);

        aman1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/8201380_unlock_padlock_password_ui_lock_icon.png"))); // NOI18N
        aman1.setText("\\");
            jPanel3.add(aman1);
            aman1.setBounds(285, 170, 8, 74);

            aman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/8201356_lock_password_padlock_privacy_ui_icon.png"))); // NOI18N
            aman.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    amanMouseClicked(evt);
                }
            });
            jPanel3.add(aman);
            aman.setBounds(173, 258, 41, 38);

            jPanel7.setLayout(new java.awt.CardLayout());
            jPanel3.add(jPanel7);
            jPanel7.setBounds(195, 290, 0, 0);

            jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
            jLabel8.setText("LOGIN");
            jPanel3.add(jLabel8);
            jLabel8.setBounds(120, 50, 52, 20);

            lihat.setBackground(new java.awt.Color(0, 204, 204));
            lihat.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    lihatMouseClicked(evt);
                }
            });
            lihat.setLayout(new java.awt.CardLayout());

            jPanel6.setBackground(new java.awt.Color(0, 204, 204));

            ntsee.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    ntseeMouseClicked(evt);
                }
            });

            javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
            jPanel6.setLayout(jPanel6Layout);
            jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ntsee, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
            );
            jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ntsee, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            );

            lihat.add(jPanel6, "card3");

            lihatlah.setBackground(new java.awt.Color(0, 204, 204));
            lihatlah.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    lihatlahMouseClicked(evt);
                }
            });

            see.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    seeMouseClicked(evt);
                }
            });

            javax.swing.GroupLayout lihatlahLayout = new javax.swing.GroupLayout(lihatlah);
            lihatlah.setLayout(lihatlahLayout);
            lihatlahLayout.setHorizontalGroup(
                lihatlahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lihatlahLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(see, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            );
            lihatlahLayout.setVerticalGroup(
                lihatlahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(see, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            );

            lihat.add(lihatlah, "card2");

            jPanel3.add(lihat);
            lihat.setBounds(244, 182, 37, 36);

            loginas.setEditable(false);
            loginas.setBackground(new java.awt.Color(0, 204, 204));
            loginas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
            loginas.setForeground(new java.awt.Color(0, 51, 204));
            loginas.setText("Kasir");
            loginas.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
            loginas.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    loginasMouseClicked(evt);
                }
            });
            loginas.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    loginasActionPerformed(evt);
                }
            });
            jPanel3.add(loginas);
            loginas.setBounds(230, 0, 70, 29);

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                    .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                    .addContainerGap())
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents
public void lihat(){
       lihat.removeAll();
        lihat.repaint();
        lihat.revalidate();

        lihat.add(ntsee);
        lihat.repaint();
        lihat.revalidate();

        txtpas.setEchoChar((char)0);
}
public void janliat(){
     lihat.removeAll();
        lihat.repaint();
        lihat.revalidate();

        lihat.add(see);
        lihat.repaint();
        lihat.revalidate();

        txtpas.setEchoChar(('*'));
}
    private void seeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seeMouseClicked
         lihat();
    }//GEN-LAST:event_seeMouseClicked

    private void ntseeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ntseeMouseClicked
         janliat();  
    }//GEN-LAST:event_ntseeMouseClicked

    private void amanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amanMouseClicked

    }//GEN-LAST:event_amanMouseClicked

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
       
        try{
            sql="Select * from login where username= '"+txtuser.getText()+"' and password='"+txtpas.getText()+"'";
           
            rs=stm.executeQuery(sql);
            if (rs.next()){
                
                if (txtuser.getText().equals(rs.getString("username"))&& txtpas.getText().equals(rs.getString("password")))
                {
                    if(loginas.getText().equalsIgnoreCase("Kasir")){
                        JOptionPane.showMessageDialog(this, "Anda berhasil Sebagai Kasir");
                      String loginAs=txtuser.getText();
       menuutama1.logiinAs=loginAs;
                        menuutama1 mn= new menuutama1();
                    mn.setVisible(true);
                    mn.setExtendedState(JFrame.MAXIMIZED_VERT);  
                    
                        System.out.println(loginAs);
                    }else{
                      JOptionPane.showMessageDialog(this, "Anda berhasil Sebagai Admin");
                       menuutama2 mn= new menuutama2();
                    mn.setVisible(true);
                    mn.setExtendedState(JFrame.MAXIMIZED_VERT);  
                    
                    }

                }
            }
        }catch(Exception e){
            JOptionPane.showConfirmDialog(this, e.getMessage());
        }txtuser.setText("");
        txtpas.setText("");
    }//GEN-LAST:event_btnloginActionPerformed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void txtuserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtuserFocusLost
                if(txtuser.getText().equals("")){
                    txtuser.setCaretPosition(0);
                    txtuser.setText("*Masukkan Username");
                }
    }//GEN-LAST:event_txtuserFocusLost

    private void txtuserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtuserFocusGained
            
//        if(txtuser.getText().equals("*Masukkan Username")){
//                    txtuser.setText("");
//                  txtuser.setFocusable(true);
//                }
       }

        private void txtnikFocusLost(java.awt.event.FocusEvent evt) {
    }//GEN-LAST:event_txtuserFocusGained

    private void txtbuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuatActionPerformed

    }//GEN-LAST:event_txtbuatActionPerformed

    private void txtbuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbuatMouseClicked
        login1 lg=new login1();
        lg.setVisible(true);
        dispose();
    }//GEN-LAST:event_txtbuatMouseClicked

    private void lihatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lihatMouseClicked

    }//GEN-LAST:event_lihatMouseClicked

    private void lihatlahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lihatlahMouseClicked

    }//GEN-LAST:event_lihatlahMouseClicked

    private void txtpasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasActionPerformed

    private void txtuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtuserMouseClicked
 if(txtuser.getText().equals("*Masukkan Username")){
                    txtuser.setText("");
                }
        
    }//GEN-LAST:event_txtuserMouseClicked

    private void txtpasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpasMouseClicked
 
    }//GEN-LAST:event_txtpasMouseClicked

    private void txtpasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasFocusGained
janliat();
if(txtpas.getText().equals("*Masukkan Password")){
    txtpas.setEchoChar(('*'));
    txtpas.setText("");
}
    }//GEN-LAST:event_txtpasFocusGained

    private void txtpasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasFocusLost
    
        if(txtpas.getText().equalsIgnoreCase("")){
            lihat();
            txtpas.setEchoChar((char)0);
    txtpas.setText("*Masukkan Password");
}
    }//GEN-LAST:event_txtpasFocusLost

    private void loginasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginasMouseClicked
        if(loginas.getText().equals("Admin")){
            loginas.setText("Kasir"); 
        }else
        loginas.setText("Admin"); 
    }//GEN-LAST:event_loginasMouseClicked

    private void loginasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginasActionPerformed

      
//    public void image(){
//       ImageIcon img=new ImageIcon("C:\\Users\\HP\\Pictures\\8201356_lock_password_padlock_privacy_ui_icon.png");
//       Image icon=img.getImage();
//     
//       Image scale=icon.getScaledInstance( aman.getWidth(),aman.getHeight(),Image.SCALE_SMOOTH);
//       ImageIcon baru= new ImageIcon(scale);
//        aman.setIcon(baru);
//
////   }public void image2(){
////       ImageIcon img=new ImageIcon("C:\\Users\\HP\\Pictures\\8201380_unlock_padlock_password_ui_lock_icon.png");
//       Image icon=img.getImage();
//     
//       Image scale=icon.getScaledInstance( aman1.getWidth(),aman1.getHeight(),Image.SCALE_SMOOTH);
//       ImageIcon baru= new ImageIcon(scale);
//        aman1.setIcon(baru);
//
//   }
      
//    public void image3(){
//       ImageIcon img=new ImageIcon("C:\\Users\\HP\\Pictures\\326497_account_circle_icon.png");
//       Image icon=img.getImage();
//     
//       Image scale=icon.getScaledInstance( jLabel4.getWidth(),jLabel4.getHeight(),Image.SCALE_SMOOTH);
//       ImageIcon baru= new ImageIcon(scale);
//        jLabel4.setIcon(baru);

   // }
  public void image6(){
       ImageIcon img=new ImageIcon("C:\\Users\\HP\\Downloads\\bukalock.png");
       Image icon=img.getImage();
     
       Image scale=icon.getScaledInstance(ntsee.getWidth(),ntsee.getHeight(),Image.SCALE_SMOOTH);
       ImageIcon baru= new ImageIcon(scale);
       ntsee.setIcon(baru);
    } public void image3(){
       ImageIcon img=new ImageIcon("C:\\Users\\HP\\Downloads\\buka.png");
       Image icon=img.getImage();
     
       Image scale=icon.getScaledInstance(see.getWidth(),see.getHeight(),Image.SCALE_SMOOTH);
       ImageIcon baru= new ImageIcon(scale);
      see.setIcon(baru);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aman;
    private javax.swing.JLabel aman1;
    private javax.swing.JToggleButton btnlogin;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel lihat;
    private javax.swing.JPanel lihatlah;
    private javax.swing.JTextField loginas;
    private javax.swing.JLabel ntsee;
    private javax.swing.JLabel see;
    private javax.swing.JTextField txtbuat;
    private javax.swing.JPasswordField txtpas;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables

}
