/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectakhir;

import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
public class menuutama2 extends javax.swing.JFrame {

  
   Connection con;
   ResultSet rs;
   Statement stm;
   String sql;
   
 
    public menuutama2() {
        initComponents();
         koneksi db=new koneksi();
        db.config();
        con=db.con;
        stm=db.stm;
        loadtable();
        //image();
      //  image2();
        total();
        
    }
   
    public void loadtable(){
        DefaultTableModel model=new DefaultTableModel();
        
         model.addColumn("no");
        model.addColumn("Kode Handphone");
        model.addColumn("Nama Handphone");
        model.addColumn("Harga");
        model.addColumn("Stok ");
        model.addColumn("Penyimpanan");
        model.addColumn("Keterangan");
        try{
            int no=1;
            sql="Select * from datahp";
            rs=stm.executeQuery(sql);
            while(rs.next()){
                model.addRow(new Object[]{no++, rs.getInt(1),rs.getString(2),rs.getInt(3),rs.getInt(4),rs.getString(5),rs.getString(6)});
            } 
        tblhp.setModel(model);
            }catch(Exception e){
    
     }

        
    }
     public void total(){
        try{
          sql="SELECT SUM(stok) FROM datahp";
          rs=stm.executeQuery(sql);
        while(rs.next()){
            int stok=rs.getInt(1);
            lblsetok.setText(String.valueOf(stok));
        }   
        }catch(Exception e){
        JOptionPane.showConfirmDialog(this, e.getMessage());
    }
        try{
          sql="SELECT SUM(jumlahbeli) FROM penjualan";
          rs=stm.executeQuery(sql);
        while(rs.next()){
            int jum=rs.getInt(1);
           
          //  lblpemasukan.setText(String.valueOf(stok));
            lblpenjualan.setText(String.valueOf(jum));
        }   
        }catch(Exception e){
        JOptionPane.showConfirmDialog(this, e.getMessage());
    }
        try{
          sql="SELECT SUM(total) FROM penjualan";
          rs=stm.executeQuery(sql);
        while(rs.next()){
            int jum=rs.getInt(1);
           
          //  lblpemasukan.setText(String.valueOf(stok));
            lblpemasukan.setText(String.valueOf(jum));
        }   
        }catch(Exception e){
        JOptionPane.showConfirmDialog(this, e.getMessage());
    }
    }
    public void insert(){
     try{
          sql="insert into datahp values('"+kodehp.getText()+"','"+namahp.getText()+"','"+hargahp.getText()+"','"+stok.getText()+"','"+txtpenyimpanan.getText()+"','"+txtket.getText()+"')";
          java.sql.PreparedStatement pst=con.prepareStatement(sql);
          pst.execute();
          JOptionPane.showConfirmDialog(null, "Penyimpanan berhasil");
          loadtable();
      }catch(Exception e){
          JOptionPane.showConfirmDialog(this, e.getMessage());
      }
    }
     public void update(){
        try{
            sql="UPDATE datahp  SET namhp='"+namahp.getText()+"',harga='"+hargahp.getText()+"',stok='"+stok.getText()+"',penyimpanan='"+txtpenyimpanan.getText()+"',keterangan='"+txtket.getText()+"' WHERE idhp='"+kodehp.getText()+"'";
            java.sql.PreparedStatement pst=con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showConfirmDialog(null, "Data berhail di update");
        }catch(Exception e){
            JOptionPane.showConfirmDialog(null, e.getMessage());
        }
    }
    public void hapus(){
        try{
            sql="delete from datahp where idhp='"+kodehp.getText()+"'";
            java.sql.PreparedStatement pst=con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showConfirmDialog(this, "Data dihapus");
        }catch(Exception e){
            JOptionPane.showConfirmDialog(this, e.getMessage());
        }
    }public void reset(){
        namahp.setText("");
        kodehp.setText("");
        hargahp.setText("");
        stok.setText("");
        txtpenyimpanan.setText("");
        txtket.setText("");
        
    }
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        viv = new javax.swing.JPanel();
        viv1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        oppo = new javax.swing.JPanel();
        oppo1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ten = new javax.swing.JPanel();
        mi4 = new javax.swing.JPanel();
        mi5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        mi = new javax.swing.JPanel();
        mi1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        oppo2 = new javax.swing.JPanel();
        oppo3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        penjualan = new javax.swing.JButton();
        pelanggan = new javax.swing.JButton();
        jPanel28 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblpemasukan = new javax.swing.JLabel();
        lblmasuk = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        lblhpjual = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblpenjualan = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        lblstok = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblsetok = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        namahp = new javax.swing.JTextField();
        stok = new javax.swing.JTextField();
        kodehp = new javax.swing.JTextField();
        hargahp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtpenyimpanan = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtket = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblhp = new javax.swing.JTable();
        seriy = new javax.swing.JPanel();
        seriy1 = new javax.swing.JPanel();
        jPanel92 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 204, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 51, 51)));

        jLabel4.setBackground(new java.awt.Color(0, 102, 102));
        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 255));
        jLabel4.setText("AMAN STORE");

        viv.setBackground(new java.awt.Color(0, 204, 51));
        viv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vivMouseClicked(evt);
            }
        });

        viv1.setBackground(new java.awt.Color(0, 204, 51));
        viv1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viv1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viv1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viv1MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                viv1MouseReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        jLabel6.setText("DATA BARANG");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout viv1Layout = new javax.swing.GroupLayout(viv1);
        viv1.setLayout(viv1Layout);
        viv1Layout.setHorizontalGroup(
            viv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viv1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        viv1Layout.setVerticalGroup(
            viv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viv1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout vivLayout = new javax.swing.GroupLayout(viv);
        viv.setLayout(vivLayout);
        vivLayout.setHorizontalGroup(
            vivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viv1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        vivLayout.setVerticalGroup(
            vivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vivLayout.createSequentialGroup()
                .addComponent(viv1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        oppo.setBackground(new java.awt.Color(0, 204, 51));

        oppo1.setBackground(new java.awt.Color(0, 204, 51));
        oppo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oppo1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                oppo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                oppo1MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                oppo1MouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        jLabel1.setText("Tentang");

        javax.swing.GroupLayout oppo1Layout = new javax.swing.GroupLayout(oppo1);
        oppo1.setLayout(oppo1Layout);
        oppo1Layout.setHorizontalGroup(
            oppo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oppo1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        oppo1Layout.setVerticalGroup(
            oppo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oppo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout oppoLayout = new javax.swing.GroupLayout(oppo);
        oppo.setLayout(oppoLayout);
        oppoLayout.setHorizontalGroup(
            oppoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oppo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        oppoLayout.setVerticalGroup(
            oppoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oppoLayout.createSequentialGroup()
                .addComponent(oppo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        ten.setBackground(new java.awt.Color(0, 204, 51));

        mi4.setBackground(new java.awt.Color(0, 204, 153));

        mi5.setBackground(new java.awt.Color(0, 204, 51));
        mi5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mi5MouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        jLabel13.setText("Keluar");

        javax.swing.GroupLayout mi5Layout = new javax.swing.GroupLayout(mi5);
        mi5.setLayout(mi5Layout);
        mi5Layout.setHorizontalGroup(
            mi5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mi5Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mi5Layout.setVerticalGroup(
            mi5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mi5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout mi4Layout = new javax.swing.GroupLayout(mi4);
        mi4.setLayout(mi4Layout);
        mi4Layout.setHorizontalGroup(
            mi4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mi5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mi4Layout.setVerticalGroup(
            mi4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mi5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout tenLayout = new javax.swing.GroupLayout(ten);
        ten.setLayout(tenLayout);
        tenLayout.setHorizontalGroup(
            tenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mi4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tenLayout.setVerticalGroup(
            tenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tenLayout.createSequentialGroup()
                .addComponent(mi4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        mi.setBackground(new java.awt.Color(0, 204, 51));

        mi1.setBackground(new java.awt.Color(0, 204, 51));
        mi1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mi1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mi1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mi1MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mi1MouseReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        jLabel8.setText("Home");

        javax.swing.GroupLayout mi1Layout = new javax.swing.GroupLayout(mi1);
        mi1.setLayout(mi1Layout);
        mi1Layout.setHorizontalGroup(
            mi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mi1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mi1Layout.setVerticalGroup(
            mi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mi1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout miLayout = new javax.swing.GroupLayout(mi);
        mi.setLayout(miLayout);
        miLayout.setHorizontalGroup(
            miLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mi1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        miLayout.setVerticalGroup(
            miLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(miLayout.createSequentialGroup()
                .addComponent(mi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        oppo2.setBackground(new java.awt.Color(0, 204, 51));

        oppo3.setBackground(new java.awt.Color(0, 204, 51));
        oppo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oppo3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                oppo3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                oppo3MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                oppo3MouseReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        jLabel2.setText("DATA Penjualan");

        javax.swing.GroupLayout oppo3Layout = new javax.swing.GroupLayout(oppo3);
        oppo3.setLayout(oppo3Layout);
        oppo3Layout.setHorizontalGroup(
            oppo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oppo3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel2)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        oppo3Layout.setVerticalGroup(
            oppo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oppo3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout oppo2Layout = new javax.swing.GroupLayout(oppo2);
        oppo2.setLayout(oppo2Layout);
        oppo2Layout.setHorizontalGroup(
            oppo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oppo3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        oppo2Layout.setVerticalGroup(
            oppo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oppo2Layout.createSequentialGroup()
                .addComponent(oppo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(oppo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(oppo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(58, 58, 58)
                .addComponent(mi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(viv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(oppo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(oppo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 0, 51)));
        jPanel1.setPreferredSize(new java.awt.Dimension(1148, 816));
        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel41.setBackground(new java.awt.Color(255, 255, 255));
        jPanel41.setPreferredSize(new java.awt.Dimension(1148, 816));
        jPanel41.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        penjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/2849824_store_shopping_market_buy_shop_icon.png"))); // NOI18N
        penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjualanActionPerformed(evt);
            }
        });
        jPanel41.add(penjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(862, 28, 0, 9));

        pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelangganActionPerformed(evt);
            }
        });
        jPanel41.add(pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 28, 0, -1));

        jPanel28.setBackground(new java.awt.Color(255, 255, 0));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel10.setText("Pemasukan");

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel14.setText("Jumlah ");

        lblpemasukan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createSequentialGroup()
                .addComponent(lblmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(lblpemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(lblpemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addComponent(lblmasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel41.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 254, -1, -1));

        jPanel33.setBackground(new java.awt.Color(0, 204, 153));

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel20.setText("Jumlah ");

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel21.setText("HP Terjual");

        lblpenjualan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addComponent(lblhpjual, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel33Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblpenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblpenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addGap(19, 19, 19))
            .addComponent(lblhpjual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel41.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 254, -1, -1));

        jPanel36.setBackground(new java.awt.Color(51, 153, 255));

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel23.setText("Stok");

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel24.setText("HP ");

        lblsetok.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addComponent(lblstok, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblsetok, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel36Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel24))
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblsetok, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addGap(19, 19, 19))
            .addComponent(lblstok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel41.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 254, -1, -1));

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel22.setText("Selamat Datang, Admin");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(615, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel22)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel41.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 900, -1));

        jPanel1.add(jPanel41, "card5");

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));

        jPanel42.setBackground(new java.awt.Color(153, 153, 153));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setText("kode Sepatu :");

        namahp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namahpActionPerformed(evt);
            }
        });

        kodehp.setForeground(new java.awt.Color(0, 0, 102));
        kodehp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodehpActionPerformed(evt);
            }
        });

        hargahp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargahpActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("Nama Sepatu :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 255));
        jLabel7.setText("Stok :");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 255, 255));
        jLabel19.setText("Harga :");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 255, 255));
        jLabel25.setText("No sepatu :");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 255, 255));
        jLabel26.setText("Keterangan :");

        txtket.setColumns(20);
        txtket.setRows(5);
        jScrollPane2.setViewportView(txtket);

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel42Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel19)
                    .addComponent(jLabel7)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namahp, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kodehp, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargahp, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stok, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpenyimpanan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel42Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kodehp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(7, 7, 7)
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namahp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hargahp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(11, 11, 11)
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtpenyimpanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel42Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButton4.setBackground(new java.awt.Color(0, 204, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 102));
        jButton4.setText("Ubah");
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("Simpan");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 204, 204));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 102));
        jButton5.setText("Hapus");
        jButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 204, 204));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 102));
        jButton6.setText("Refresh");
        jButton6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        tblhp.setBackground(new java.awt.Color(204, 204, 204));
        tblhp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblhp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblhp.setOpaque(false);
        tblhp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblhpMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblhp);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(50, 50, 50))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(217, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel19, "card5");

        seriy.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout seriyLayout = new javax.swing.GroupLayout(seriy);
        seriy.setLayout(seriyLayout);
        seriyLayout.setHorizontalGroup(
            seriyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1144, Short.MAX_VALUE)
        );
        seriyLayout.setVerticalGroup(
            seriyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 812, Short.MAX_VALUE)
        );

        jPanel1.add(seriy, "card2");

        seriy1.setBackground(new java.awt.Color(0, 204, 153));

        jPanel92.setBackground(new java.awt.Color(0, 102, 102));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 255, 255));
        jLabel9.setText("oppo");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel92Layout = new javax.swing.GroupLayout(jPanel92);
        jPanel92.setLayout(jPanel92Layout);
        jPanel92Layout.setHorizontalGroup(
            jPanel92Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel92Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1012, Short.MAX_VALUE))
        );
        jPanel92Layout.setVerticalGroup(
            jPanel92Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel92Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout seriy1Layout = new javax.swing.GroupLayout(seriy1);
        seriy1.setLayout(seriy1Layout);
        seriy1Layout.setHorizontalGroup(
            seriy1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seriy1Layout.createSequentialGroup()
                .addComponent(jPanel92, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        seriy1Layout.setVerticalGroup(
            seriy1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seriy1Layout.createSequentialGroup()
                .addComponent(jPanel92, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(746, Short.MAX_VALUE))
        );

        jPanel1.add(seriy1, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(95, 95, 95))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// public void image(){
//        ImageIcon img=new ImageIcon("C:\\Users\\HP\\Pictures\\2849824_store_shopping_market_buy_shop_icon.png");
//        Image icon=img.getImage();
//      
//       Image scale=icon.getScaledInstance( penjualan.getWidth(),penjualan.getHeight(),Image.SCALE_SMOOTH);
//        ImageIcon baru= new ImageIcon(scale);
//        penjualan.setIcon(baru);
//
//   }
// public void image2(){
//        ImageIcon img=new ImageIcon("C:\\Users\\HP\\Downloads\\customer.png");
//        Image icon=img.getImage();
//      
//       Image scale=icon.getScaledInstance( pelanggan.getWidth(),pelanggan.getHeight(),Image.SCALE_SMOOTH);
//        ImageIcon baru= new ImageIcon(scale);
//       pelanggan.setIcon(baru);
//
//   }


    private void penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjualanActionPerformed
        
    }//GEN-LAST:event_penjualanActionPerformed

    private void pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelangganActionPerformed
//        cekout ck=new cekout();
//        ck.setVisible(true);
//        
    }//GEN-LAST:event_pelangganActionPerformed

    private void oppo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oppo1MouseClicked
mi1.setBackground(new Color(0,204,51));
viv1.setBackground(new Color(0,204,51));
oppo1.setBackground(Color.YELLOW);
oppo3.setBackground(new Color(0,204,51));
     tentang t=new tentang();
     t.setVisible(true);
     t.setLocationRelativeTo(null);
    }//GEN-LAST:event_oppo1MouseClicked

    private void viv1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viv1MouseClicked
viv1.setBackground(Color.YELLOW);
mi1.setBackground(new Color(0,204,51));
oppo1.setBackground(new Color(0,204,51));
oppo3.setBackground(new Color(0,204,51));
        jPanel1.removeAll();
        jPanel1.repaint();
        jPanel1.revalidate();

        jPanel1.add(jPanel19);
        jPanel1.repaint();
        jPanel1.revalidate();      
    }//GEN-LAST:event_viv1MouseClicked

    private void mi1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mi1MouseClicked
mi1.setBackground(Color.YELLOW);
viv1.setBackground(new Color(0,204,51));
oppo1.setBackground(new Color(0,204,51));
oppo3.setBackground(new Color(0,204,51));
        jPanel1.removeAll();
        jPanel1.repaint();
        jPanel1.revalidate();

        jPanel1.add(jPanel41);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_mi1MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void viv1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viv1MouseReleased
//viv1.setBackground(new Color(0,204,135));         
    }//GEN-LAST:event_viv1MouseReleased

    private void mi5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mi5MouseClicked
login n=new login();
n.setVisible(true);
n.setLocationRelativeTo(null);
        mi5.setBackground(Color.YELLOW);
       dispose();
    }//GEN-LAST:event_mi5MouseClicked

    private void oppo1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oppo1MouseReleased
        oppo.setBackground(Color.YELLOW);
    }//GEN-LAST:event_oppo1MouseReleased

    private void mi1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mi1MouseReleased
       mi.setBackground(Color.YELLOW);
       
    }//GEN-LAST:event_mi1MouseReleased

    private void vivMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vivMouseClicked
      viv1.setBackground(Color.YELLOW);
    }//GEN-LAST:event_vivMouseClicked

    private void viv1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viv1MouseEntered
        viv.setBackground(Color.RED);
    }//GEN-LAST:event_viv1MouseEntered

    private void oppo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oppo1MouseEntered
       oppo.setBackground(Color.RED);
    }//GEN-LAST:event_oppo1MouseEntered

    private void mi1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mi1MouseExited
          mi.setBackground(new Color(0,204,51));
    }//GEN-LAST:event_mi1MouseExited

    private void viv1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viv1MouseExited
         viv.setBackground(new Color(0,204,51));
    }//GEN-LAST:event_viv1MouseExited

    private void mi1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mi1MouseEntered
       mi.setBackground(Color.RED);
    }//GEN-LAST:event_mi1MouseEntered

    private void oppo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oppo1MouseExited
         oppo.setBackground(new Color(0,204,51));
    }//GEN-LAST:event_oppo1MouseExited

    private void oppo3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oppo3MouseClicked
        cekout1 ck=new cekout1();
        ck.setVisible(true);
        ck.setLocationRelativeTo(null);
        oppo3.setBackground(Color.YELLOW);
        oppo1.setBackground(new Color(0,204,51));
viv1.setBackground(new Color(0,204,51));
mi1.setBackground(new Color(0,204,51));
    }//GEN-LAST:event_oppo3MouseClicked

    private void oppo3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oppo3MouseEntered
   oppo2.setBackground(Color.RED);
    }//GEN-LAST:event_oppo3MouseEntered

    private void oppo3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oppo3MouseExited

        oppo2.setBackground(new Color(0,204,51));
        
    }//GEN-LAST:event_oppo3MouseExited

    private void oppo3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oppo3MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_oppo3MouseReleased

    private void namahpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namahpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namahpActionPerformed

    private void kodehpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodehpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodehpActionPerformed

    private void hargahpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargahpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargahpActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        update();
        loadtable();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        insert();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        hapus();
        loadtable();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        reset();
        kodehp.setEditable(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tblhpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhpMouseClicked
        int baris=tblhp.rowAtPoint(evt.getPoint());
        String kode=tblhp.getValueAt(baris, 1).toString();
        kodehp.setText(kode);
        String nama=tblhp.getValueAt(baris, 2).toString();
        namahp.setText(nama);
        String harga=tblhp.getValueAt(baris, 3).toString();
        hargahp.setText(harga);
        String stokhp=tblhp.getValueAt(baris, 4).toString();
        stok.setText(stokhp);
        String simpan=tblhp.getValueAt(baris, 5).toString();
        txtpenyimpanan.setText(simpan);
        String keterangan=tblhp.getValueAt(baris, 6).toString();
        txtket.setText(keterangan);

        kodehp.setEditable(false);
    }//GEN-LAST:event_tblhpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuutama2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuutama2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuutama2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuutama2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuutama2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hargahp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel92;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kodehp;
    private javax.swing.JLabel lblhpjual;
    private javax.swing.JLabel lblmasuk;
    private javax.swing.JLabel lblpemasukan;
    private javax.swing.JLabel lblpenjualan;
    private javax.swing.JLabel lblsetok;
    private javax.swing.JLabel lblstok;
    private javax.swing.JPanel mi;
    private javax.swing.JPanel mi1;
    private javax.swing.JPanel mi4;
    private javax.swing.JPanel mi5;
    private javax.swing.JTextField namahp;
    private javax.swing.JPanel oppo;
    private javax.swing.JPanel oppo1;
    private javax.swing.JPanel oppo2;
    private javax.swing.JPanel oppo3;
    private javax.swing.JButton pelanggan;
    private javax.swing.JButton penjualan;
    private javax.swing.JPanel seriy;
    private javax.swing.JPanel seriy1;
    private javax.swing.JTextField stok;
    private javax.swing.JTable tblhp;
    private javax.swing.JPanel ten;
    private javax.swing.JTextArea txtket;
    private javax.swing.JTextField txtpenyimpanan;
    private javax.swing.JPanel viv;
    private javax.swing.JPanel viv1;
    // End of variables declaration//GEN-END:variables
}
